### ISSUE TITLE
Nuget package does note create a markdown file

### ISSUE THREAD

**Issue by snielsson** [Pxtl/XmlCommentMarkDownGenerator#6]
Hi

I have a project  with xml docs enabled in both debug and release. I get xml files generated when I build. 
I have now installed  XmlCommentMarkDownGenerator 

**Install-Package PxtlCa.XmlCommentMarkDownGenerator**

Now when I rebuild I do not see any markdown files generated anywhere. I dont see a Docs folder next to the solution folder. Also, I dont see anything added to the csproj file ?

**Comment by Pxtl** [comment]
Oof, evidently I broke the target thing at some point.  It should still work as a command-line tool but I'm going to look and find what needs to be reverted.

**Comment by Pxtl** [comment]
Thanks for the heads up, I'm an imbecile - apparently the one nuget package where this actually worked was an experimental fluke and I never actually committed the reference to the .targets file.

Get the latest nuget package.  Totally fixes it.  And the .targets are visible in packages\PxtlCa.XmlCommentMarkDownGenerator.0.2.6130.564\build

**Comment by FLAMESpl** [comment]
Hi

I have the same problem as snielsson except I have already installed 0.2.6130.564 and use dotnet core 1.0.1. I don't see individual configuration for release and debug, but the xml file seems to be generated in both targets.

**Comment by Pxtl** [comment]
I haven't done any testing on dotnet core... have you checked in Packages\yaddayaddayadda\build for the Targets file?
